project:
  type: website
  output-dir: docs
  
website:
  title: "Futurverse - UseR! 2024"
  navbar:
    left:
      - text: "Part 1"
        menu:
          - text: "Slides Part 1 (pdf)"
            url:  BengtssonH_20240612-futureverse-part1-user2024.pdf
          - text: "Lab 1"
            href: lab1.qmd
      - text: "Part 2"
        menu:
          - text: "Slides Part 2 (pdf)"
            url:  BengtssonH_20240612-futureverse-part2-user2024.pdf
          - text: "Lab 2"
            href: lab2.qmd
        
  search: 
    location: navbar
    type: overlay
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
