project:
  type: website
  output-dir: docs
  
website:
  title: "Futurverse - UseR! 2024"
  navbar:
    left:
      - text: "Part 1"
        menu:
          - text: "Slides Part 1 (online)"
            url:  https://docs.google.com/presentation/d/1O_0FHwj1kB6JXK4Z1n8-H5h00GS8nzs4P7KY6Bknais/edit?usp=sharing
          - text: "Lab 1"
            href: lab1.qmd
      - text: "Part 2"
        menu:
          - text: "Slides Part 2 (online)"
            url:  https://docs.google.com/presentation/d/1DNtO52spuqElppac4OL7Ov8jUTzD_vrlD1dXtQ7sUmY/edit?usp=sharing
          - text: "Lab 2"
            href: lab2.qmd
        
  search: 
    location: navbar
    type: overlay
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
